# 에러 처리

## try ... catch ... finally문
`try ... catch ... finally`문으로 에러 발생 시 에러를 처리할 수 있다.

```js
try {
  // 실행할 코드 
} catch(err) {
  // try 코드 블록에서 에러 발생 시 실행되는 코드 블럭
  // err에는 try 코드 블럭에서 발생한 Error 객체가 전달됨
} finally {
  // 에러 발생과 상관없이 실행되는 코드 블럭
}
```

<br/>

## Error 객체
Error 생성자 함수를 통해 에러 객체를 생성할 수 있다. 에러 객체는 에러 메세지인 message 프로퍼티와 에러를 발생시킨 콜스택의 호출정보를 나타내는 문자열인 stack 프로퍼티를 갖는다. stack 프로퍼티는 디버깅 목적으로 사용한다.
```js
const error = new Error('invalid');
```

#### 7가지의 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공한다. 모두 Error.prototype을 상속받는다.
- Error : 일반적 에러 객체
- SyntaxError : 자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체
- ReferenceError : 참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체
- TypeError : 피연산자 또는 인수의 데이터 타입이 유효하지 않을 때 발생하는 에러 객체
- RangeError : 숫자값의 허용 범위를 벗어났을 때 발생하는 에러 객체
- URIError : encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체
- EvalError : eval 함수에서 발생하는 에러 객체

```js
1 @ 1;    // SyntaxError: Invalid or unexpected token
foo();    // ReferenceError: foo is not defined
null.foo; // TypeError: Cannot read property 'foo' of null
new Array(-1); // RangeError: Invalid array length
decodeURIComponent('%'); // URIError: URI malformed
```

<br/>

## throw 문
`throw`문으로 에러를 발생시킬 수 있다.
```js
try {
  // 에러 객체를 던지면 catch 코드 블록이 실행되기 시작한다.
  throw new Error('error');
} catch (error) {
  console.log(error);
}
```


